name: Release

on:
  push:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Set up Repository
        uses: actions/checkout@v2
        with:
          ref: master

      - name: Set up Node
        uses: actions/setup-node@v2
        with:
          node-version: 14

      - name: Cache Node Modules
        uses: actions/cache@v2
        with:
          path: node_modules
          key: ${{ runner.OS }}-yarn-${{ hashFiles('**/yarn.lock') }}
          restore-keys: |
            ${{ runner.OS }}-yarn-

      - name: Yarn Install
        run: |
          yarn

      - name: Build
        run: |
          yarn build

      - name: Upload Artifacts
        uses: actions/upload-artifact@v2
        with:
          name: dist
          path: dist

  commit-bundle:
    needs: build
    runs-on: ubuntu-latest
    steps:
      - name: Check diff
        uses: technote-space/get-diff-action@v6
        with:
          PATTERNS: |
            **/*.(ts|js|json)

      - name: Set up Repository
        uses: actions/checkout@v2
        with:
          ref: bundle

      - name: Download Bundle
        uses: actions/download-artifact@v2
        with:
          name: dist
          path: dist

      - name: Commit and Push
        run: |
          git config user.name github-actions
          git config user.email github-actions@github.com
          git add dist
          git commit -m "chore: updated bundle"
          git push origin HEAD --force
        if: env.GIT_DIFF
